version: '2.2'

services:

#  traefik:
#    image: traefik:1.7
#    command: --docker --docker.exposedbydefault=false
#    ports:
#      - "80:81"
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock

  app:
    image: thecodingmachine/php:7.3-v2-apache-node10
    labels:
      - traefik.enable=true
      - traefik.backend=app
      - traefik.frontend.rule=Host:127.0.0.1
    ports:
      - "8080:80"
    environment:
      APACHE_DOCUMENT_ROOT: "public/"
      PHP_EXTENSION_XDEBUG: "1"
      PHP_INI_MEMORY_LIMIT: "1G"
      # Symfony
      APP_ENV: "dev"
      APP_SECRET: "8d2a5c935d8ef1c0e2b751147382bc75"
      DATABASE_URL: "mysql://$MYSQL_USER:$MYSQL_PASSWORD@mysql:3306/$MYSQL_DATABASE"
    volumes:
      - ./app:/var/www/html:rw
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "projet_CA"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "root"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./services/mysql/utf8mb4.cnf:/etc/mysql/conf.d/utf8mb4.cnf:ro

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    labels:
      - traefik.enable=true
      - traefik.backend=phpmyadmin
      - traefik.frontend.rule=Host:127.0.0.1
    ports:
      - "8181:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: "root"
      PMA_PASSWORD: "root"

volumes:
  mysql_data:
      driver: local